name: qbet
base: core22
version: '1.0.0-omega'
title: QBET Sovereign Engine
summary: Sovereign Reality Creation Language
description: |
  QBET is a sovereign programming language for quantum-spiritual manifestation.
  It moves beyond classical "source code" into a Declaration of Reality, 
  enforced by the hard 3-layer Authoritative Model (Creation, Execution, Law).
  Governed by opendev-labs.
license: MIT
contact: yashramteke55555@gmail.com
website: https://opendev-labs.github.io/QBET/
issues: https://github.com/opendev-labs/QBET/issues

grade: stable
confinement: strict

parts:
  qbet:
    plugin: dump
    source: .
    build-packages:
      - python3-pip
    override-build: |
      craftctl default
      chmod +x $CRAFT_PART_INSTALL/qb
      mkdir -p $CRAFT_PART_INSTALL/bin
      ln -sf ../qb $CRAFT_PART_INSTALL/bin/qbet
      # Sync standard deps
      pip3 install flask requests --target $CRAFT_PART_INSTALL/lib/python3.10/site-packages

apps:
  qbet:
    command: qb
    plugs:
      - network
      - network-bind
      - home
  portal:
    command: qb portal
    plugs:
      - network
      - network-bind
      - home
