name: qbet
base: core22
version: '1.0.0-omega'
title: QBET Sovereign Engine
summary: Sovereign Reality Creation Language
icon: assets/logo.png
description: |
  QBET (Quantum Binding & Emergence Toolchain) is a sovereign creation language 
  designed for deterministic reality manifestation. Unlike classical imperative 
  languages, QBET operates on a 3-layer Authoritative Model that separates 
  intention (Creation Layer) from mechanical execution (Execution Layer), 
  all governed by the immutable Kernel Law Contract.

  Key Features:
  - Sovereign Conduction: Translate declarative intent into low-level IR.
  - Quantum Metaphysics: Native support for metaphorical world-building and state collapse.
  - Deterministic Execution: Law-bound runtime ensuring coherence across all universes.
  - Unified Toolchain: Includes the Omega-grade CLI Conductor and Visual Portal.

  Governed exclusively by opendev-labs.
license: MIT
contact: yashramteke55555@gmail.com
website: https://opendev-labs.github.io/QBET/
issues: https://github.com/opendev-labs/QBET/issues

grade: stable
confinement: strict

parts:
  qbet:
    plugin: dump
    source: .
    build-packages:
      - python3-pip
    override-build: |
      craftctl default
      chmod +x $CRAFT_PART_INSTALL/qb
      mkdir -p $CRAFT_PART_INSTALL/bin
      ln -sf ../qb $CRAFT_PART_INSTALL/bin/qbet
      # Sync standard deps
      pip3 install flask requests --target $CRAFT_PART_INSTALL/lib/python3.10/site-packages

apps:
  qbet:
    command: qb
    plugs:
      - network
      - network-bind
      - home
  portal:
    command: qb portal
    plugs:
      - network
      - network-bind
      - home
